services:
  backend:
    image: ${DOCKER_IMAGE_BE}
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./hydroponic_be:/app:Z
      - py_venv:/app/.venv
    build:
      context: .
      dockerfile: hydroponic_be/Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}/${POSTGRES_DB}
      MQTT_BROKER: broker
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
  frontend:
    image: ${DOCKER_IMAGE_FE}
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./hydroponic_fe:/app:Z
      - node_modules:/app/node_modules
    build:
      context: .
      dockerfile: hydroponic_fe/Dockerfile
    depends_on:
      - backend
  db:
    image: "postgres:18.3-alpine"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro,Z
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  broker:
    image: ${DOCKER_IMAGE_BROKER}
    restart: unless-stopped
    build:
      context: .
      dockerfile: mosquitto/Dockerfile
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "health", "-m", "ok", "-u", "${MQTT_USERNAME}", "-P", "${MQTT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  py_venv:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
  pgdata:
    driver: local
  node_modules:
    driver: local