services:
  backend:
    image: ${DOCKER_IMAGE_BE}
    restart: unless-stopped
    ports:
      - "8000:8000"
    # Only accessible to the host Nginx on this machine
    # ports:
    #   - "127.0.0.1:8000:8000"
    # Use this for local development only
    # volumes:
    #   - ./hydroponic_be:/app:Z
    #   - py_venv:/app/.venv
    # Comment this for build the image
    # build:
    #   context: .
    #   dockerfile: hydroponic_be/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${APP_DB_USER}:${APP_DB_PASSWORD}@${POSTGRES_SERVER}/${POSTGRES_DB}
      MQTT_BROKER: broker
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
      db-initializer:
        condition: service_completed_successfully
    networks:
      - hydroponic_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  frontend:
    image: ${DOCKER_IMAGE_FE}
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Only accessible to the host Nginx on this machine
    # ports:
    #   - "127.0.0.1:3000:3000"
    # Use this for local development only
    # volumes:
    #   - ./hydroponic_fe:/app:Z
    #   - node_modules:/app/node_modules
    # build:
    #   context: .
    #   dockerfile: hydroponic_fe/Dockerfile
    depends_on:
      - backend
    networks:
      - hydroponic_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  db-initializer:
    image: "postgres:18.3-alpine"
    restart: "no" # Do not restart; it runs once and shuts down
    env_file:
      - .env
    volumes:
      # Mount your configuration script into the initialization container
      - ./scripts/init-db.sh:/init-db.sh:ro,Z
    entrypoint: ["/bin/sh", "/init-db.sh"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hydroponic_net

  db:
    image: "postgres:18.3-alpine"
    restart: unless-stopped
    # Completely hidden from the host system; accessible only to FastAPI internally
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro,Z
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hydroponic_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  broker:
    image: ${DOCKER_IMAGE_BROKER}
    restart: unless-stopped
    build:
      context: .
      dockerfile: mosquitto/Dockerfile
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "health", "-m", "ok", "-u", "${MQTT_USERNAME}", "-P", "${MQTT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hydroponic_net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

networks:
  hydroponic_net:
    driver: bridge

volumes:
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
  pgdata:
    driver: local