"""initial tables

Revision ID: 6f836d5b5076
Revises: 
Create Date: 2026-03-18 00:32:05.424264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '6f836d5b5076'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commandstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attr', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attr', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devicetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attr', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attr', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mac_addr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('devicetype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['devicetype_id'], ['devicetype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandlog',
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commandtype.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['commandstatus.id'], ),
    sa.PrimaryKeyConstraint('command_id', 'status_id', 'device_id', 'timestamp')
    )
    op.create_index(op.f('ix_commandlog_command_id'), 'commandlog', ['command_id'], unique=False)
    op.create_index(op.f('ix_commandlog_device_id'), 'commandlog', ['device_id'], unique=False)
    op.create_index(op.f('ix_commandlog_status_id'), 'commandlog', ['status_id'], unique=False)
    op.create_index(op.f('ix_commandlog_timestamp'), 'commandlog', ['timestamp'], unique=False)
    op.create_table('datalog',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('data_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datalog')
    op.drop_index(op.f('ix_commandlog_timestamp'), table_name='commandlog')
    op.drop_index(op.f('ix_commandlog_status_id'), table_name='commandlog')
    op.drop_index(op.f('ix_commandlog_device_id'), table_name='commandlog')
    op.drop_index(op.f('ix_commandlog_command_id'), table_name='commandlog')
    op.drop_table('commandlog')
    op.drop_table('device')
    op.drop_table('devicetype')
    op.drop_table('commandtype')
    op.drop_table('commandstatus')
    # ### end Alembic commands ###
