"""initial tables

Revision ID: c4387f97f1e6
Revises: 
Create Date: 2026-03-09 17:27:19.425147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4387f97f1e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmdstat')
    op.drop_table('cmddef')
    op.drop_index(op.f('ix_datalog_rack_id'), table_name='datalog')
    op.drop_table('datalog')
    op.drop_table('rack')
    op.drop_index(op.f('ix_cmdlog_rack_id'), table_name='cmdlog')
    op.drop_index(op.f('ix_cmdlog_timestamp'), table_name='cmdlog')
    op.drop_table('cmdlog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmdlog',
    sa.Column('command_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rack_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['cmddef.id'], name=op.f('cmdlog_command_id_fkey')),
    sa.ForeignKeyConstraint(['rack_id'], ['rack.id'], name=op.f('cmdlog_rack_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['cmdstat.id'], name=op.f('cmdlog_status_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cmdlog_pkey'))
    )
    op.create_index(op.f('ix_cmdlog_timestamp'), 'cmdlog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_cmdlog_rack_id'), 'cmdlog', ['rack_id'], unique=False)
    op.create_table('rack',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rack_pkey'))
    )
    op.create_table('datalog',
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('data_log', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('rack_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['rack.id'], name=op.f('datalog_rack_id_fkey')),
    sa.PrimaryKeyConstraint('timestamp', 'rack_id', name=op.f('datalog_pkey'))
    )
    op.create_index(op.f('ix_datalog_rack_id'), 'datalog', ['rack_id'], unique=False)
    op.create_table('cmddef',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cmddef_pkey'))
    )
    op.create_table('cmdstat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cmdstat_pkey'))
    )
    # ### end Alembic commands ###
