"""add cmd_log column

Revision ID: ef32fa5a14d8
Revises: 6f836d5b5076
Create Date: 2026-04-12 07:45:13.707682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef32fa5a14d8'
down_revision: Union[str, Sequence[str], None] = '6f836d5b5076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commandlog', sa.Column('cmd_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commandlog', 'cmd_log')
    # ### end Alembic commands ###
